name: tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'  # or your project's version

      - name: Install dependencies
        run: npm ci
        working-directory: ./api

      - name: Run Jest tests
        run: npm run test
        working-directory: ./api
        env:
          MONGODB_URI: mongodb://0.0.0.0/jumper-generator-test-database  # Make sure this runs Jest
